# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
font_size 13.0
symbol_map U+4E00-U+9FFF,U+3400-U+4DBF Maple Mono NF CN

clipboard_control write-clipboard read-clipboard write-primary read-primary
clipboard_max_size 64          

# BEGIN_KITTY_FONTS
font_family      family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# window
background_opacity        0.85
padding_background_opacity 0.90   # 必须同显式写出，否则内边距区域不透明
dynamic_background_opacity no
background_blur 30
remember_window_size  yes
allow_remote_control yes
enabled_layouts splits,fat,grid,horizontal,stack,tall,vertical
cursor_trail 3

# tab bar
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled

# 垂直分屏（左右）
map alt+\ launch --location=vsplit --cwd=current

# 水平分屏（上下）
map alt+- launch --location=hsplit --cwd=current

map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

