local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local rep = require("luasnip.extras").rep

return {
	s({ trig = "init_path", desc = "创建swiftUI NavigationPath" }, { -- 触发词
		t("@Binding private var "),
		i(1, "path"),
		t(": NavigationPath"),
		t({ "", "" }), -- 换行
		t("init(path: Binding<NavigationPath>) {"),
		t({ "", "    self._" }),
		i(2, "path"),
		t(" = "),
		rep(2),
		t({ "", "}" }),
	}),
	s({ trig = "init_viewModel_action", desc = "创建action viewModel" }, {
		t("//MARK: - Action"),
		t({ "", "" }),
		t("extension "),
		i(1, "ViewModel"),
		t(" {"),
		t({ "", "" }),
		t("    enum Action {"),
		t({ "", "" }),
		t("        "),
		i(2, "// Define your actions here"),
		t({ "", "" }),
		t("    }"),
		t({ "", "" }),
		t({ "", "" }),
		t("    func send(_ action: Action) {"),
		t({ "", "" }),
		t("        Task {"),
		t({ "", "" }),
		t("            await sendWithAsync(action)"),
		t({ "", "" }),
		t("        }"),
		t({ "", "" }),
		t("    }"),
		t({ "", "" }),
		t({ "", "" }),
		t("    func sendWithAsync(_ action: Action) async {"),
		t({ "", "" }),
		t("        switch action {"),
		t({ "", "" }),
		t("            "),
		i(3, "// Handle different actions"),
		t({ "", "" }),
		t("        }"),
		t({ "", "" }),
		t("    }"),
		t({ "", "" }),
		t({ "", "" }),
		t("}"),
		t({ "", "" }),
		t({ "", "" }),
		t("//MARK: - Private Methods"),
		t({ "", "" }),
		t("private extension "),
		i(4, "ViewModel"),
		t(" {"),
		t({ "", "" }),
		t("    "),
		i(5, "// Add your private helper methods here"),
		t({ "", "" }),
		t("}"),
	}),
	s("init_network", {
		t("//MARK: - 网络协议"),
		t({ "", "" }),
		t({ "", "" }),
		t("struct "),
		i(1, "Name"),
		t("Server: "),
		i(2, "name"),
		t("NetworkProtocol"),
		t(" {"),
		t({ "", "" }),
		t({ "", "" }),
		t("    func request"),
		i(3, "Name"),
		t("() async throws -> "),
		i(4, "Result"),
		t(" {"),
		t({ "", "" }),
		t("        "),
		i(5, "// Implementation here"),
		t({ "", "" }),
		t("    }"),
		t({ "", "" }),
		t("}"),
		t({ "", "" }),
		t({ "", "" }),
		t("protocol "),
		i(6, "name"),
		t("NetworkProtocol: Sendable {"),
		t({ "", "" }),
		t({ "", "" }),
		t("    func request"),
		i(7, "Name"),
		t("() async throws -> "),
		i(8, "Result"),
		t(""),
		t({ "", "" }),
		t("}"),
	}),
}
