local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local rep = require("luasnip.extras").rep

return {
	s("lazy_stackV", {
		t("private lazy var "),
		i(1, "stackV"),
		t(": UIStackView = {"),
		t({ "", "    let " }),
		rep(1),
		t(" = UIStackView()"),
		t({ "", "    " }),
		rep(1),
		t(".axis = .vertical"),
		t({ "", "    " }),
		rep(1),
		t(".isLayoutMarginsRelativeArrangement = true"),
		t({ "", "    " }),
		rep(1),
		t(".directionalLayoutMargins = .init("),
		t({ "", "        top: " }),
		i(2, "0"),
		t({ ",", "        leading: " }),
		i(3, "0"),
		t({ ",", "        bottom: " }),
		i(4, "0"),
		t({ ",", "        trailing: " }),
		i(5, "0"),
		t({ "", "    )" }),
		t({ "", "    " }),
		rep(1),
		t(".spacing = "),
		i(6, "8"),
		t({ "", "    " }),
		rep(1),
		t(".insetsLayoutMarginsFromSafeArea = false"),
		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_table", {
		t("private lazy var "),
		i(1, "tableV"),
		t(": UITableView = {"),
		t({ "", "    let " }),
		rep(1),
		t(" = UITableView(frame: .zero, style: .plain)"),
		t({ "", "    " }),
		rep(1),
		t(".backgroundColor = .clear"),
		t({ "", "    " }),
		rep(1),
		t(".separatorStyle = .none"),
		t({ "", "    " }),
		rep(1),
		t(".showsVerticalScrollIndicator = false"),
		t({ "", "    " }),
		rep(1),
		t(".tableFooterView = UIView()"),
		t({ "", "    " }),
		rep(1),
		t(".dataSource = self"),
		t({ "", "    " }),
		rep(1),
		t(".delegate = self"),
		t({ "", "    " }),
		rep(1),
		t(".rowHeight = UITableView.automaticDimension"),
		t({ "", "    // " }),
		rep(1),
		t(".register(cellWithClass: "),
		i(2, "TableViewCell"),
		t(".self)"),
		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_btn_config", {
		t("private lazy var "),
		i(1, "btn"),
		t(": UIButton = {"),

		t({ "", "    var config = UIButton.Configuration.filled()" }),
		t({ "", "    config.title = " }),
		i(2, '"Button"'),

		t({ "", "    // config.imagePlacement = .trailing" }),
		t({ "", "    // config.imagePadding = 4" }),

		t({ "", "    config.baseForegroundColor = .black" }),
		t({ "", "    config.baseBackgroundColor = .clear" }),
		t({ "", "    config.contentInsets = .zero" }),

		t({ "", "    config.titleTextAttributesTransformer = UIConfigurationTextAttributesTransformer { incoming in" }),
		t({ "", "        var outgoing = incoming" }),
		t({ "", "        outgoing.font = UIFont.systemFont(ofSize: 24, weight: .semibold)" }),
		t({ "", "        return outgoing" }),
		t({ "", "    }" }),

		t({ "", "" }),
		t({ "", "    let " }),
		rep(1),
		t(" = UIButton(configuration: config)"),

		t({ "", "    // " }),
		rep(1),
		t(".configurationUpdateHandler = { button in"),
		t({ "", "    //     guard var updatedConfig = button.configuration else {" }),
		t({ "", "    //         return" }),
		t({ "", "    //     }" }),
		t({ "", "    //     button.configuration = updatedConfig" }),
		t({ "", "    // }" }),

		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_view", {
		t("private lazy var "),
		i(1, "view"),
		t(": UIView = {"),
		t({ "", "    let " }),
		rep(1),
		t(" = UIView()"),
		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_label", {
		t("private lazy var "),
		i(1, "label"),
		t(": UILabel = {"),
		t({ "", "    let " }),
		rep(1),
		t(" = UILabel()"),
		t({ "", "    " }),
		rep(1),
		t(".font = .systemFont(ofSize: 14, weight: .medium)"),
		t({ "", "    " }),
		rep(1),
		t(".numberOfLines = 0"),
		t({ "", "    " }),
		rep(1),
		t(".textColor = .black"),
		t({ "", "    " }),
		rep(1),
		t(".text = "),
		i(2, '"Label"'),
		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_scrollView", {
		t("private lazy var "),
		i(1, "scrollView"),
		t(": UIScrollView = {"),
		t({ "", "    let " }),
		rep(1),
		t(" = UIScrollView()"),
		t({ "", "    if #available(iOS 11.0, *) {" }),
		t({ "", "        " }),
		rep(1),
		t(".contentInsetAdjustmentBehavior = .never"),
		t({ "", "        " }),
		rep(1),
		t(".scrollIndicatorInsets = "),
		rep(1),
		t(".contentInset"),
		t({ "", "    }" }),
		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_textField", {
		t("private lazy var "),
		i(1, "textField"),
		t(": UITextField = {"),
		t({ "", "    let " }),
		rep(1),
		t(" = UITextField()"),
		t({ "", "    " }),
		rep(1),
		t(".textColor = .black"),
		t({ "", "    " }),
		rep(1),
		t(".font = .systemFont(ofSize: 16, weight: .medium)"),
		t({ "", "    " }),
		rep(1),
		t(".placeholder = "),
		i(2, '"placeholder"'),
		t({ "", "    " }),
		rep(1),
		t(".clearButtonMode = .always"),
		t({ "", "    " }),
		rep(1),
		t(".autocapitalizationType = .none"),
		t({ "", "    return " }),
		rep(1),
		t({ "", "}()" }),
	}),
	s("lazy_imageView", {
		t("private lazy var "),
		i(1, "imageView"),
		t(": UIImageView = {"),
		t({ "", "    let imageV = UIImageView(image: UIImage(named: " }),
		i(2, '"imageName"'),
		t("))"),
		t({ "", "    imageV.contentMode = .scaleAspectFit" }),
		t({ "", "    return imageV" }),
		t({ "", "}()" }),
	}),
	s("lazy_single_view_withVM", {
		t("private lazy var "),
		i(1, "name"),
		t(": "),
		i(2, "ViewClass"),
		t(" = .init(viewModel: viewModel)"),
	}),
}
